server:
  port: 9001
spring:
  datasource:
    url: jdbc:h2:mem:teaching_db_schema
    driverClassName: org.h2.Driver
    username: mike
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    #     ddl-auto: validate
    generate-ddl: false
    show-sql: false
  h2:
    console:
      path: /h2
      enabled: true
#  flyway:
#    user: mike
#    password: 1234
##    url: jdbc:h2:study:teaching_db_schema
#    locations: classpath:db/migration
#    clean-disabled: false
#    clean-on-validation-error: false